version: "3.9"

services:
  app:
    image: my-app:v1.0.1
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3000
    networks:
      - my-node-app
    profiles:
      - all
      - app
  
  db:
    image: postgres
    hostname: localhost
    container_name: db
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
      POSTGRES_DB: restaurant_db
    ports:
      - 5432:5432
    networks:
      - my-node-app
    volumes:
      - .db-data:/var/lib/postgresql/data
    profiles:
      - all
      - db
  
  pg-admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - 8888:80
    networks:
      - my-node-app
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_LISTEN_PORT: "80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    profiles:
      - all
      - db

volumes:
  pgadmin-data:

networks:
  my-node-app: 
    driver: bridge